name: Tests on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests-on-pr:
    uses: scikit-package/release-scripts/.github/workflows/_tests-on-pr-no-codecov.yml@v0
    with:
      project: diffpy.srxplanargui
      c_extension: false
      headless: false
      run: |
        conda install pre-commit
        pre-commit run --all-files
